apiVersion: v1
kind: Secret
metadata:
  name: learning-feed-secrets
  namespace: learning-feed
  labels:
    app: learning-feed-generator
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded secrets
  # To encode: echo -n "your-secret-here" | base64
  OPENAI_API_KEY: "" # Add your base64 encoded OpenAI API key
  PERPLEXITY_API_KEY: "" # Add your base64 encoded Perplexity API key
  NOTION_TOKEN: "" # Add your base64 encoded Notion token
  NOTION_DATABASE_ID: "" # Add your base64 encoded Notion database ID
---
# Example secret template with placeholders
# To use this, create your secrets with kubectl:
# kubectl create secret generic learning-feed-secrets \
#   --from-literal=OPENAI_API_KEY="your-openai-key" \
#   --from-literal=PERPLEXITY_API_KEY="your-perplexity-key" \
#   --from-literal=NOTION_TOKEN="your-notion-token" \
#   --from-literal=NOTION_DATABASE_ID="your-database-id" \
#   --namespace=learning-feed

